name : Chocolatine

env:
  MIRROR_URL: ${{ secrets.MIRROR_URL }}
  EXECUTABLES: ${{ secrets.EXECUTABLES }}


on:
  push:
    branches-ignore: [ga-ignore-*]
  pull_request:
    branches-ignore: [ga-ignore-*]

jobs:
  check_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check if mirror
        run: |
          if [ "${{ github.event.repository.clone_url }}" = "${{ env.MIRROR_URL }}" ]; then
            echo "This is a mirror repository, skipping workflow"
            exit 1
          fi

  check_coding_style:
    needs: check_mirror
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run coding style
        run: |
          check.sh $(pwd) $(pwd)
          if [ -s "coding-style-reports.log" ]; then
            while IFS= read -r line; do
              file=$(echo "$line" | cut -d: -f1)
              line_num=$(echo "$line" | cut -d: -f2)
              error=$(echo "$line" | cut -d: -f3-)
              echo "::error file=$file,line=$line_num::$error"
            done < coding-style-reports.log
            exit 1
          fi
  
  check_program_compilation:
    needs: check_mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential make gcc
        
      - name: make
        run: |
          make
        timeout-minutes: 2
        
      - name: make_clean
        run: |
          make clean
        
      - name: Check executables
        run: |
          for exec in ${{ env.EXECUTABLES }}; do
            if [ ! -x "$exec" ]; then
              echo "Error: '$exec' not found or not executable"
              exit 1
            fi
            echo "Executable '$exec' found and is executable"
          done